name: Test Python 🐍 package

on:
  push:
    branches: [main, dev]
    paths-ignore:
      - "**.md"
      - "**.bib"
      - "**.ya?ml"
      - "LICENSE"
      - ".gitignore"
      - "**.ipynb"
  pull_request:
    branches: [main, dev]
    types: [opened, reopened]
    paths-ignore:
      - "**.md"
      - "**.bib"
      - "**.ya?ml"
      - "LICENSE"
      - ".gitignore"
      - "**.ipynb"
  workflow_dispatch:
  workflow_call:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13"]

    steps:
      - uses: actions/checkout@v5

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v6
        with:
          python-version: ${{ matrix.python-version }}

      - name: Display Python version
        run: python -c "import sys; print(sys.version)"

      - name: Install dev dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]

      - name: Install pybada manually
        run: pip install pybada --ignore-requires-python --no-deps

      - name: Checkout BADA data repo
        uses: actions/checkout@v5
        with:
          repository: eurocontrol-asu/bada-data
          token: ${{ secrets.DATA_REPO_TOKEN }}
          path: bada_data
      
      - name: Copy XML data files
        run: |
          mkdir -p tests/data/BADA/3.16
          mkdir -p tests/data/BADA/4.2.1/A320-231
          mkdir -p tests/data/BADA/4.2.1/B772RL
          cp bada_data/*.OPF tests/data/BADA/3.16/
          cp bada_data/A320-231.xml tests/data/BADA/4.2.1/A320-231/A320-231.xml
          cp bada_data/B772RL.xml tests/data/BADA/4.2.1/B772RL/B772RL.xml
          cp bada_data/GPF.xml tests/data/BADA/4.2.1/GPF.xml

      - name: Run tests
        run: |
          pip install pytest pytest-cov
          pytest --cov=pyneats --cov-report=xml --cov-report=term-missing tests/